sonar.projectKey=EPSI_Security_Design
sonar.organization=gregoire-mouilleau

sonar.projectName=EPSI_Security_Design
sonar.projectVersion=1.0

# Sources
sonar.sources=backend,frontend

# Exclusions
sonar.exclusions=**/node_modules/**,**/assets/**,**/*.test.js,**/*.spec.js

sonar.sourceEncoding=UTF-8
