import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 34,
    paddingHorizontal: 16,
  },
  frameGlow: {
    width: '100%',
    borderRadius: 34,
    borderWidth: 5,
    borderColor: '#D89A2E',
    backgroundColor: 'rgba(70, 11, 0, 0.76)',
    paddingHorizontal: 12,
    paddingTop: 72,
    paddingBottom: 16,
    shadowColor: '#FACC15',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.75,
    shadowRadius: 22,
  },
  backButton: {
    position: 'absolute',
    top: 12,
    right: 14,
    backgroundColor: 'rgba(122, 23, 7, 0.98)',
    borderColor: '#F9BC29',
    borderWidth: 2,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 17,
    zIndex: 40,
    shadowColor: '#FBBF24',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  backButtonText: {
    color: '#FDE047',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 0.4,
  },
  topBanner: {
    position: 'absolute',
    top: -28,
    left: 16,
    right: 16,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7B1F0F',
    borderWidth: 3,
    borderColor: '#E1A02C',
    borderRadius: 24,
    paddingVertical: 10,
    paddingHorizontal: 20,
    gap: 8,
    shadowColor: '#FBBF24',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
  },
  topBannerEmoji: {
    fontSize: 30,
  },
  topBannerTitle: {
    color: '#FDE047',
    fontSize: 34,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  panel: {
    width: '100%',
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 24,
    backgroundColor: '#EFD2A0',
    borderWidth: 3.4,
    borderColor: '#D69832',
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
});

export default styles;
