import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 220,
  },
  profileButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(139, 0, 0, 0.5)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: '#FFD700',
    borderBottomWidth: 4,
    zIndex: 200,
    transition: Platform.OS === 'web' ? 'all 0.3s ease' : undefined,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
  },
  profileButtonHovered: {
    backgroundColor: 'rgba(255, 215, 0, 0.4)',
    borderColor: '#FFF',
    transform: [{ scale: 1.08 }],
    shadowColor: '#FFD700',
    shadowOpacity: 0.9,
    shadowRadius: 20,
  },
  profileIcon: {
    fontSize: 26,
    marginRight: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 3,
  },
  profileText: {
    color: '#FFD700',
    fontSize: 15,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  profileAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    marginRight: 8,
    borderWidth: 2,
    borderColor: '#FFD700',
  },
  mascot: {
    position: 'absolute',
    top: 20,
    left: 20,
    opacity: 0.95,
    zIndex: 100,
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  eloTouchable: {
    position: 'absolute',
    right: -110,
    zIndex: 100,
  },
  eloBadge: {
    width: '100%',
    height: '100%',
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  rulesBadge: {
    position: 'absolute',
    left: -30,
    zIndex: 100,
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  hamburgerButton: {
    position: 'absolute',
    top: 20,
    left: 20,
    backgroundColor: 'rgba(139, 0, 0, 0.6)',
    paddingVertical: 11,
    paddingHorizontal: 13,
    borderRadius: 14,
    borderWidth: 3,
    borderColor: '#FFD700',
    borderBottomWidth: 4,
    zIndex: 200,
    gap: 5,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
  hamburgerBar: {
    width: 24,
    height: 3,
    backgroundColor: '#FFD700',
    borderRadius: 2,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'flex-end',
  },
  menuPanel: {
    backgroundColor: '#3C0A00',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderTopWidth: 4,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderColor: '#D89A2E',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 32,
    maxHeight: '80%',
  },
  menuHandle: {
    width: 44,
    height: 5,
    backgroundColor: '#D89A2E',
    borderRadius: 3,
    alignSelf: 'center',
    marginBottom: 14,
    opacity: 0.7,
  },
  menuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(216, 154, 46, 0.3)',
    paddingBottom: 12,
  },
  menuTitle: {
    color: '#FDE047',
    fontSize: 22,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0,0,0,0.4)',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 4,
  },
  menuClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(216, 154, 46, 0.25)',
    borderWidth: 2,
    borderColor: '#D89A2E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuCloseText: {
    color: '#FDE047',
    fontSize: 16,
    fontWeight: 'bold',
  },
  menuItem: {
    alignItems: 'center',
    marginBottom: 12,
    backgroundColor: 'rgba(216, 154, 46, 0.08)',
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: 'rgba(216, 154, 46, 0.3)',
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  menuBadgeImage: {
    width: '100%',
    height: 180,
  },
  menuItemLabel: {
    color: '#FDE047',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1.2,
    marginTop: 4,
    marginBottom: 4,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
});
