import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    container: {
        width: '90%',
        maxWidth: 600,
        backgroundColor: '#1a1a2e',
        borderRadius: 20,
        padding: 30,
        borderWidth: 3,
        borderColor: '#FFD700',
        alignItems: 'center',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#FFD700',
        marginBottom: 10,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 16,
        color: '#FFFFFF',
        marginBottom: 30,
        textAlign: 'center',
    },
    choicesContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 20,
        gap: 15,
    },
    choiceWrapper: {
        alignItems: 'center',
        gap: 10,
    },
    choiceButton: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 140,
        height: 140,
        borderRadius: 70,
        borderWidth: 4,
        borderColor: '#FFD700',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        shadowColor: '#FFD700',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    choiceButtonSelected: {
        borderColor: '#FFD700',
        backgroundColor: 'rgba(255, 215, 0, 0.25)',
        borderWidth: 5,
        shadowOpacity: 0.8,
        shadowRadius: 15,
        transform: [{ scale: 1.05 }],
    },
    choiceImage: {
        width: 90,
        height: 90,
    },
    choiceName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFD700',
        textAlign: 'center',
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    waitingContainer: {
        marginTop: 20,
        padding: 20,
        backgroundColor: 'rgba(255, 215, 0, 0.15)',
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255, 215, 0, 0.3)',
    },
    waitingText: {
        fontSize: 18,
        color: '#FFD700',
        textAlign: 'center',
        fontWeight: '600',
    },
    resultContainer: {
        width: '100%',
        alignItems: 'center',
    },
    vsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 30,
    },
    resultChoice: {
        alignItems: 'center',
    },
    resultPlayerName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFD700',
        marginBottom: 10,
    },
    resultImage: {
        width: 100,
        height: 100,
        marginBottom: 10,
    },
    resultChoiceName: {
        fontSize: 14,
        color: '#FFFFFF',
    },
    vsText: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FFD700',
        marginHorizontal: 20,
    },
    resultText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#FFD700',
        textAlign: 'center',
        lineHeight: 30,
    },
});
