import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    zIndex: 2,
  },
  buttonsContainer: {
    width: '100%',
    maxWidth: 400,
    gap: 20,
    marginTop: 16,
  },
  decorativeElements: {
    marginTop: 50,
    alignItems: 'center',
  },
  chipGroup: {
    flexDirection: 'row',
    gap: 20,
  },
  chip: {
    fontSize: 40,
    textShadowColor: 'rgba(255, 215, 0, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  settingsArea: {
    position: 'absolute',
    left: 20,
    bottom: 20,
    zIndex: 120,
  },
  settingsEmojiTouch: {
    width: 86,
    height: 86,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsEmoji: {
    shadowColor: 'rgba(0, 0, 0, 0.6)',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.7,
    shadowRadius: 12,
  },
  settingsPanel: {
    width: '78%',
    maxWidth: 760,
    minWidth: 340,
    backgroundColor: 'rgba(70, 11, 0, 0.76)',
    borderWidth: 5,
    borderColor: '#D89A2E',
    borderRadius: 28,
    paddingVertical: 28,
    paddingHorizontal: 28,
    shadowColor: '#D89A2E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.65,
    shadowRadius: 24,
    elevation: 10,
  },
  settingsOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 160,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  settingsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  settingsTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  settingsTitleEmoji: {
    fontSize: 26,
    textShadowColor: 'rgba(253, 224, 71, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  settingsPanelTitle: {
    color: '#FDE047',
    fontSize: 24,
    fontWeight: 'bold',
    letterSpacing: 2.5,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 4,
  },
  closeButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: '#D89A2E',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(216, 154, 46, 0.18)',
  },
  closeButtonText: {
    color: '#FDE047',
    fontSize: 18,
    fontWeight: 'bold',
  },
  settingsDivider: {
    height: 2,
    backgroundColor: 'rgba(216, 154, 46, 0.3)',
    marginVertical: 16,
    borderRadius: 1,
  },
  settingRow: {
    marginBottom: 20,
  },
  settingLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  settingEmoji: {
    fontSize: 18,
    textShadowColor: 'rgba(253, 224, 71, 0.4)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  settingLabel: {
    color: '#F6DEB2',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 1,
  },
  volumeControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  smallControlButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(216, 154, 46, 0.25)',
    borderWidth: 2.5,
    borderColor: '#D89A2E',
    shadowColor: '#D89A2E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  smallControlButtonText: {
    color: '#FDE047',
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: -2,
  },
  settingValue: {
    color: '#FDE047',
    minWidth: 80,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  inlineActionButton: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(216, 154, 46, 0.25)',
    borderWidth: 2.5,
    borderColor: '#D89A2E',
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 20,
    shadowColor: '#D89A2E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  inlineActionButtonText: {
    color: '#FDE047',
    fontWeight: 'bold',
    fontSize: 15,
    letterSpacing: 1.5,
  },
  disconnectButton: {
    marginTop: 8,
    backgroundColor: 'rgba(216, 154, 46, 0.15)',
    borderWidth: 2.5,
    borderColor: '#D89A2E',
    borderRadius: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#D89A2E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  disconnectButtonEmoji: {
    fontSize: 16,
  },
  disconnectButtonText: {
    color: '#FDE047',
    fontWeight: 'bold',
    letterSpacing: 1.2,
    fontSize: 14,
  },
  historyButton: {
    borderWidth: 1.5,
    borderColor: 'rgba(201,168,76,0.5)',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(201,168,76,0.08)',
  },
  historyButtonText: {
    color: '#C9A84C',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
});

export default styles;
