import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    zIndex: 2,
  },
  buttonsContainer: {
    width: '100%',
    maxWidth: 400,
    gap: 20,
    marginTop: 16,
  },
  decorativeElements: {
    marginTop: 50,
    alignItems: 'center',
  },
  chipGroup: {
    flexDirection: 'row',
    gap: 20,
  },
  chip: {
    fontSize: 40,
    textShadowColor: 'rgba(255, 215, 0, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  settingsArea: {
    position: 'absolute',
    left: 20,
    bottom: 20,
    zIndex: 120,
  },
  settingsEmojiTouch: {
    width: 86,
    height: 86,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsEmoji: {
    shadowColor: 'rgba(0, 0, 0, 0.6)',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.7,
    shadowRadius: 12,
  },
  settingsPanel: {
    width: '78%',
    maxWidth: 760,
    minWidth: 340,
    backgroundColor: 'rgba(139, 0, 0, 0.7)',
    borderWidth: 4,
    borderColor: '#FFD700',
    borderRadius: 28,
    paddingVertical: 22,
    paddingHorizontal: 22,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.55,
    shadowRadius: 18,
  },
  settingsOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 160,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  settingsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  settingsPanelTitle: {
    color: '#FFD700',
    fontSize: 22,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  closeButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.18)',
  },
  closeButtonText: {
    color: '#FFD700',
    fontSize: 18,
    fontWeight: 'bold',
  },
  settingRow: {
    marginBottom: 16,
  },
  settingLabel: {
    color: '#FFF',
    fontSize: 14,
    marginBottom: 8,
    fontWeight: '600',
    letterSpacing: 0.8,
  },
  volumeControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  smallControlButton: {
    width: 34,
    height: 34,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    borderWidth: 2,
    borderColor: '#FFD700',
  },
  smallControlButtonText: {
    color: '#FFD700',
    fontSize: 22,
    fontWeight: 'bold',
    marginTop: -1,
  },
  settingValue: {
    color: '#FFF',
    minWidth: 70,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  inlineActionButton: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 215, 0, 0.18)',
    borderWidth: 2,
    borderColor: '#FFD700',
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 16,
  },
  inlineActionButtonText: {
    color: '#FFD700',
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  disconnectButton: {
    marginTop: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 2,
    borderColor: '#FFD700',
    borderRadius: 16,
    paddingVertical: 10,
    alignItems: 'center',
  },
  disconnectButtonText: {
    color: '#FFD700',
    fontWeight: 'bold',
    letterSpacing: 1.1,
    fontSize: 13,
  },
});

export default styles;
