import { StyleSheet } from 'react-native';

export const SCALE_HEIGHT = 600;

const styles = StyleSheet.create({
  loading: {
    paddingVertical: 40,
    zIndex: 10,
  },
  errorContainer: {
    paddingVertical: 40,
    paddingHorizontal: 20,
    alignItems: 'center',
    zIndex: 10,
  },
  errorText: {
    color: '#7B1F0F',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: 'bold',
  },
  retryButton: {
    backgroundColor: '#7B1F0F',
    borderColor: '#E1A02C',
    borderWidth: 2,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  retryButtonText: {
    color: '#FDE047',
    fontSize: 16,
    fontWeight: 'bold',
  },
  mainContent: {
    flexDirection: 'row',
    gap: 16,
    zIndex: 10,
    minHeight: 550,
  },
  leftSection: {
    flex: 1.2,
    minWidth: 420,
  },
  rightSection: {
    flex: 1,
    minWidth: 380,
  },
  sectionHeader: {
    backgroundColor: '#6D2110',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#D59A34',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#FDE047',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  scaleContainer: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 10,
    flex: 1,
  },
  scaleContent: {
    width: 380,
    height: SCALE_HEIGHT,
    position: 'relative',
    paddingLeft: 180,
    paddingRight: 180,
    justifyContent: 'flex-end',
  },
  scaleVerticalLine: {
    position: 'absolute',
    left: '50%',
    marginLeft: -2,
    bottom: 0,
    width: 4,
    height: SCALE_HEIGHT,
    backgroundColor: '#8B4513',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  rankSegment: {
    position: 'absolute',
    left: '50%',
    marginLeft: -15,
    width: 30,
    borderWidth: 1,
    borderRadius: 15,
    opacity: 0.8,
  },
  rankPoint: {
    position: 'absolute',
    left: '50%',
    marginLeft: -8,
    width: 16,
    height: 16,
    zIndex: 5,
  },
  rankDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: '#5A2C0D',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  rankLabelContainer: {
    position: 'absolute',
    left: 24,
    top: -10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFD2A0',
    borderRadius: 12,
    borderWidth: 2.5,
    borderColor: '#8B4513',
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    minWidth: 140,
    justifyContent: 'space-between',
  },
  rankLabelLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  rankEmoji: {
    fontSize: 18,
  },
  rankNameText: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  rankEloText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#5A2C0D',
    marginLeft: 10,
  },
  topPlayerConnector: {
    position: 'absolute',
    height: 3,
    backgroundColor: '#FFA500',
    zIndex: 8,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
  },
  topPlayerMarker: {
    position: 'absolute',
    right: -190,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFD700',
    borderRadius: 16,
    borderWidth: 3,
    borderColor: '#FFA500',
    paddingVertical: 10,
    paddingHorizontal: 12,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.7,
    shadowRadius: 12,
    zIndex: 10,
    minWidth: 160,
  },
  crownBadge: {
    position: 'absolute',
    top: -16,
    left: 6,
    zIndex: 5,
  },
  crownEmoji: {
    fontSize: 28,
  },
  topPlayerAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 3,
    borderColor: '#FFF',
  },
  topPlayerInfo: {
    flex: 1,
  },
  topPlayerPseudo: {
    color: '#7B1F0F',
    fontSize: 15,
    fontWeight: 'bold',
  },
  topPlayerElo: {
    color: '#8B4513',
    fontSize: 14,
    fontWeight: 'bold',
  },
  currentPlayerArrowLine: {
    position: 'absolute',
    left: 162,
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 8,
    borderBottomWidth: 8,
    borderLeftWidth: 12,
    borderRightWidth: 0,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#6D2110',
    borderRightColor: 'transparent',
    zIndex: 9,
  },
  currentPlayerMarker: {
    position: 'absolute',
    left: 85,
    backgroundColor: '#6D2110',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#D89A2E',
    paddingVertical: 6,
    paddingHorizontal: 10,
    zIndex: 10,
    shadowColor: '#D89A2E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
  },
  currentPlayerPseudo: {
    color: '#FDE047',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  topPlayersContainer: {
    flex: 1,
  },
  topPlayersList: {
    maxHeight: SCALE_HEIGHT + 40,
  },
  playerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(113, 28, 11, 0.3)',
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: 'rgba(213, 154, 52, 0.4)',
  },
  playerItemHighlight: {
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    borderColor: '#D59A34',
    borderWidth: 3,
  },
  playerPosition: {
    width: 40,
    alignItems: 'center',
  },
  playerPositionText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFD700',
  },
  playerItemAvatar: {
    width: 45,
    height: 45,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#D59A34',
    marginRight: 10,
  },
  playerItemInfo: {
    flex: 1,
  },
  playerItemPseudo: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#5A2C0D',
    marginBottom: 2,
  },
  playerItemRank: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  playerItemRankEmoji: {
    fontSize: 12,
    marginRight: 4,
  },
  playerItemRankText: {
    fontSize: 13,
    color: '#8B4513',
    fontWeight: 'bold',
  },
  playerItemElo: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#7B1F0F',
    marginLeft: 8,
  },
});

export default styles;
