import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  loading: {
    paddingVertical: 40,
  },
  userBox: {
    gap: 8,
  },
  profileTopCard: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 18,
    borderWidth: 2.2,
    borderColor: '#D59A34',
    backgroundColor: '#6D2110',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 3,
  },
  topCardSparkles: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.85,
  },
  sparkle: {
    position: 'absolute',
    color: '#FDE68A',
    fontSize: 15,
    textShadowColor: 'rgba(255, 234, 165, 0.75)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 9,
  },
  sparkleOne: {
    top: 10,
    left: 180,
  },
  sparkleTwo: {
    top: 56,
    right: 170,
    fontSize: 13,
  },
  sparkleThree: {
    bottom: 16,
    left: 28,
    fontSize: 11,
  },
  currentAvatarRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    gap: 10,
  },
  currentUserInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 2,
  },
  avatarFrame: {
    width: 94,
    height: 94,
    borderRadius: 47,
    borderWidth: 3,
    borderColor: '#F2C14A',
    backgroundColor: '#5B1408',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FACC15',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.45,
    shadowRadius: 7,
  },
  currentAvatar: {
    width: 78,
    height: 78,
    borderRadius: 39,
    borderWidth: 2,
    borderColor: '#F5D17B',
  },
  usernameSlot: {
    flex: 1,
    minHeight: 56,
    borderRadius: 14,
    borderWidth: 1.6,
    borderColor: 'rgba(247, 195, 86, 0.45)',
    backgroundColor: 'rgba(113, 28, 11, 0.55)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  profileNameValue: {
    color: '#F9E08F',
    fontSize: 30,
    fontWeight: 'bold',
    letterSpacing: 0.4,
  },
  eloBadge: {
    minWidth: 150,
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(100, 23, 10, 0.95)',
    borderWidth: 2.4,
    borderColor: '#F1B63E',
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 14,
    zIndex: 2,
    shadowColor: '#FACC15',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  rankHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  rankEmoji: {
    fontSize: 22,
  },
  rankName: {
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  eloLabel: {
    color: '#FDE68A',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.9,
  },
  eloValue: {
    color: '#FFF6C7',
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  progressBarContainer: {
    width: '100%',
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 3,
    overflow: 'hidden',
    marginTop: 4,
    marginBottom: 3,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  eloToNext: {
    color: '#FDE68A',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  maxRankText: {
    color: '#FFD700',
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 4,
  },
  eloCoin: {
    position: 'absolute',
    bottom: 6,
    right: 8,
    fontSize: 20,
    opacity: 0.88,
  },
  ruleBlock: {
    backgroundColor: 'rgba(246, 222, 178, 0.95)',
    borderWidth: 2,
    borderColor: '#CE903A',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: '#8B5A2B',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.16,
    shadowRadius: 3,
  },
  ruleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  ruleNumber: {
    width: 34,
    height: 34,
    lineHeight: 30,
    borderRadius: 10,
    backgroundColor: '#B91C1C',
    borderWidth: 2,
    borderColor: '#F59E0B',
    textAlign: 'center',
    color: '#FDE047',
    fontWeight: 'bold',
    fontSize: 22,
  },
  sectionTitle: {
    color: '#5B2100',
    fontWeight: 'bold',
    fontSize: 34,
  },
  label: {
    color: '#78350F',
    fontWeight: 'bold',
    marginTop: 3,
    marginBottom: 4,
    fontSize: 17,
  },
  pseudoInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  changesBadge: {
    backgroundColor: '#DC2626',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  changesBadgeText: {
    color: '#FEF3C7',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 0.3,
  },
  currentPseudoHint: {
    marginBottom: 3,
  },
  currentPseudoHintText: {
    color: '#92400E',
    fontSize: 13,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  securityRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  securityCol: {
    flex: 1,
    minWidth: 240,
  },
  input: {
    borderWidth: 1.8,
    borderColor: '#C08024',
    backgroundColor: 'rgba(255, 245, 214, 0.92)',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    color: '#3F1D00',
    fontWeight: '600',
    marginBottom: 8,
    fontSize: 15,
  },
  modeRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  modeButton: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#B45309',
    borderRadius: 14,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FAE9BF',
  },
  modeButtonActive: {
    backgroundColor: '#F59E0B',
  },
  modeButtonText: {
    color: '#7C2D12',
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 0.4,
  },
  modeButtonTextActive: {
    color: '#FFF8DB',
  },
  buttonsRow: {
    gap: 10,
  },
  actionsWrap: {
    alignItems: 'center',
    gap: 9,
    paddingBottom: 2,
  },
  actionButton: {
    width: '100%',
    maxWidth: 540,
    backgroundColor: '#8E1E13',
    borderWidth: 2.4,
    borderColor: '#E4A12F',
    borderRadius: 999,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 6,
    shadowColor: '#FACC15',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  secondaryButton: {
    width: '100%',
    maxWidth: 540,
    backgroundColor: 'rgba(249, 232, 189, 0.85)',
    borderWidth: 2,
    borderColor: '#C88D30',
    borderRadius: 999,
    paddingVertical: 11,
    alignItems: 'center',
    marginTop: 6,
  },
  debugButton: {
    width: '100%',
    maxWidth: 540,
    backgroundColor: '#7C3AED',
    borderWidth: 2,
    borderColor: '#A78BFA',
    borderRadius: 999,
    paddingVertical: 8,
    alignItems: 'center',
    marginTop: 6,
  },
  disabledButton: {
    opacity: 0.5,
  },
  disabledButtonLook: {
    opacity: 0.7,
  },
  actionButtonText: {
    color: '#FDE047',
    fontWeight: 'bold',
    letterSpacing: 0.9,
    fontSize: 16,
  },
  secondaryButtonText: {
    color: '#7C2D12',
    fontWeight: 'bold',
    letterSpacing: 0.7,
    fontSize: 14,
  },
  debugButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    letterSpacing: 0.5,
    fontSize: 13,
  },
  message: {
    color: '#5A2100',
    marginTop: 12,
    marginBottom: 6,
    textAlign: 'left',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 20,
    backgroundColor: 'rgba(251, 233, 195, 0.95)',
    borderWidth: 2,
    borderColor: '#D4A65A',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    shadowColor: '#8B5A2B',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 6,
  },
  avatarOption: {
    borderRadius: 28,
    borderWidth: 2.4,
    borderColor: '#CC8F31',
    backgroundColor: '#F4D9A0',
    padding: 2,
  },
  avatarOptionSelected: {
    borderColor: '#7C2D12',
    shadowColor: '#7C2D12',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
  avatarOptionImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
});

export default styles;
