import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
        padding: 20,
    },
    card: {
        backgroundColor: 'rgba(70, 11, 0, 0.76)',
        padding: 40,
        borderRadius: 34,
        borderWidth: 5,
        borderColor: '#D89A2E',
        alignItems: 'center',
        maxWidth: 500,
        width: '100%',
        shadowColor: '#FACC15',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.75,
        shadowRadius: 22,
        elevation: 10,
    },
    emoji: {
        fontSize: 60,
        marginBottom: 20,
        textShadowColor: 'rgba(250, 204, 21, 0.8)',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 20,
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FDE047',
        marginBottom: 15,
        textAlign: 'center',
        letterSpacing: 1,
        textShadowColor: 'rgba(0, 0, 0, 0.8)',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 4,
    },
    text: {
        fontSize: 16,
        color: '#F6DEB2',
        textAlign: 'center',
        lineHeight: 24,
    },
    leaveButton: {
        marginTop: 30,
        backgroundColor: 'rgba(122, 23, 7, 0.98)',
        paddingVertical: 15,
        paddingHorizontal: 40,
        borderRadius: 999,
        borderWidth: 2,
        borderColor: '#F9BC29',
        shadowColor: '#FBBF24',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 5,
    },
    leaveButtonText: {
        color: '#FDE047',
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
        letterSpacing: 0.4,
    },
    vsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        width: '100%',
        marginTop: 20,
        marginBottom: 20,
    },
    playerCard: {
        backgroundColor: 'rgba(123, 31, 15, 0.6)',
        padding: 15,
        borderRadius: 12,
        borderWidth: 3,
        borderColor: '#E1A02C',
        alignItems: 'center',
        minWidth: 120,
        shadowColor: '#FBBF24',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
    },
    avatarImage: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginBottom: 10,
        borderWidth: 3,
        borderColor: '#D89A2E',
    },
    playerEmoji: {
        fontSize: 40,
        marginBottom: 10,
    },
    playerName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FDE047',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    vsText: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#DC2626',
        textShadowColor: 'rgba(0, 0, 0, 0.8)',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 4,
        marginHorizontal: 10,
    },
    startingText: {
        fontSize: 18,
        color: '#A3E635',
        fontWeight: 'bold',
        marginTop: 10,
        textShadowColor: 'rgba(0, 0, 0, 0.6)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
});
