import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  dice: {
    width: 56,
    height: 56,
    backgroundColor: '#F5E4BB',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    borderTopColor: '#FFF8E7',
    borderLeftColor: '#FFF8E7',
    borderBottomColor: '#8B6A14',
    borderRightColor: '#8B6A14',
    shadowColor: '#1A0A00',
    shadowOffset: { width: 3, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 10,
    position: 'relative',
  },
  lockedDice: {
    backgroundColor: '#C8900A',
    borderTopColor: '#FFD060',
    borderLeftColor: '#FFD060',
    borderBottomColor: '#7A5008',
    borderRightColor: '#7A5008',
  },
  emptyDice: {
    backgroundColor: '#C8B89A',
    borderTopColor: '#DDD0B8',
    borderLeftColor: '#DDD0B8',
    borderBottomColor: '#7A6A4A',
    borderRightColor: '#7A6A4A',
    opacity: 0.5,
  },
  rollingDice: {
    backgroundColor: '#FFF0A0',
    borderTopColor: '#FFFACC',
    borderLeftColor: '#FFFACC',
    borderBottomColor: '#A08420',
    borderRightColor: '#A08420',
  },
  dot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    position: 'absolute',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.35,
    shadowRadius: 1,
    elevation: 2,
  },
  'top-left':     { top: 10, left: 10 },
  'top-right':    { top: 10, right: 10 },
  'center':       { top: '50%', left: '50%', marginTop: -4.5, marginLeft: -4.5 },
  'middle-left':  { top: '50%', left: 10, marginTop: -4.5 },
  'middle-right': { top: '50%', right: 10, marginTop: -4.5 },
  'bottom-left':  { bottom: 10, left: 10 },
  'bottom-right': { bottom: 10, right: 10 },
});
