import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: '#0a0a0a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bgPattern: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundImage: Platform.OS === 'web'
      ? 'repeating-linear-gradient(45deg, transparent, transparent 35px, rgba(139, 0, 0, 0.1) 35px, rgba(139, 0, 0, 0.1) 70px), repeating-linear-gradient(-45deg, transparent, transparent 35px, rgba(255, 215, 0, 0.05) 35px, rgba(255, 215, 0, 0.05) 70px)'
      : undefined,
  },
  bgGradient: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundImage: Platform.OS === 'web'
      ? 'radial-gradient(ellipse at top, rgba(139, 0, 0, 0.4) 0%, transparent 60%), radial-gradient(ellipse at bottom, rgba(255, 215, 0, 0.2) 0%, transparent 60%), linear-gradient(180deg, rgba(10,10,10,0.8) 0%, rgba(139,0,0,0.3) 50%, rgba(0,0,0,0.9) 100%)'
      : undefined,
  },
  diceLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
  },
  card: {
    backgroundColor: 'rgba(15, 5, 5, 0.95)',
    borderRadius: 24,
    padding: 32,
    width: '88%',
    maxWidth: 440,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 30,
    elevation: 20,
  },
  iconWrapper: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(220, 20, 60, 0.2)',
    borderWidth: 2,
    borderColor: '#DC143C',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
    shadowColor: '#DC143C',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  icon: {
    fontSize: 40,
  },
  errorIcon: {
    fontSize: 56,
    marginBottom: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFD700',
    marginBottom: 10,
    textAlign: 'center',
    textShadowColor: 'rgba(255, 215, 0, 0.4)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
    letterSpacing: 1,
  },
  message: {
    fontSize: 15,
    color: '#CCCCCC',
    textAlign: 'center',
    marginBottom: 22,
    lineHeight: 22,
  },
  infoCard: {
    backgroundColor: 'rgba(220, 20, 60, 0.08)',
    borderRadius: 14,
    padding: 18,
    marginBottom: 20,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.25)',
  },
  infoRow: {
    paddingVertical: 4,
  },
  infoDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 215, 0, 0.15)',
    marginVertical: 10,
  },
  infoLabel: {
    fontSize: 13,
    color: '#999999',
    marginBottom: 3,
  },
  infoValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  infoValueHighlight: {
    color: '#FFD700',
  },
  question: {
    fontSize: 15,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: '600',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
    marginBottom: 16,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },
  resumeButton: {
    backgroundColor: '#DC143C',
    borderColor: '#FF4444',
    shadowColor: '#DC143C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
  },
  newGameButton: {
    backgroundColor: 'transparent',
    borderColor: '#FFD700',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  homeLink: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    marginTop: 4,
    width: '100%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeLinkText: {
    color: '#CCCCCC',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
});
