import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    alignItems: 'center',
    marginVertical: 8,
  },
  labelContainer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FFD700',
    marginBottom: 10,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 8,
  },
  inactiveLabel: {
    backgroundColor: 'rgba(50, 50, 50, 0.6)',
    borderColor: '#888888',
    shadowOpacity: 0,
  },
  labelText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFF',
    letterSpacing: 1.2,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  timerBox: {
    width: 120,
    height: 120,
    backgroundColor: 'rgba(70, 11, 0, 0.95)',
    borderRadius: 60,
    borderWidth: 5,
    borderColor: '#FFD700',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 15,
  },
  inactiveBox: {
    backgroundColor: 'rgba(40, 40, 40, 0.7)',
    borderColor: '#666666',
    shadowOpacity: 0.2,
  },
  urgentBox: {
    backgroundColor: 'rgba(139, 0, 0, 0.95)',
  },
  timerValue: {
    fontSize: 48,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  timerUnit: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFD700',
    marginTop: -5,
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});
